export const additionalServicesData = {
  "general-physician": {
    id: "general-physician",
    title: "General Physician",
    h1: "Best General Physician in Patna | Comprehensive Health Checkups",
    seoTitle: "Best General Physician in Patna | Avni Hospital",
    description: "Consult the best general physicians at Avni Hospital, Patna. We offer expert diagnosis and treatments for fevers, infections, and chronic diseases.",
    keywords: "general physician patna, best doctor in bihar, fever treatment patna, internal medicine",
    intro: "Our General Physicians at Avni Hospital provide the first line of defense for your health. We offer accurate diagnoses and comprehensive care for a wide range of acute and chronic medical conditions, ensuring holistic well-being.",
    whatIsIt: "A general physician is a medical doctor who provides non-surgical care, focusing on preventive medicine, health education, and the treatment of adult diseases.",
    symptoms: ["High fever", "Chronic fatigue", "Unexplained weight loss", "Severe body ache", "Breathing difficulties"],
    causes: ["Viral or bacterial infections", "Lifestyle factors", "Environmental changes", "Metabolic disorders", "Stress"],
    diagnosis: "Thorough clinical examination supported by advanced pathology and radiology diagnostics.",
    treatments: [
      { title: "Infectious Diseases", desc: "Treatment for malaria, dengue, typhoid, and seasonal flu." },
      { title: "Chronic Disease Management", desc: "Care for diabetes, hypertension, and thyroid disorders." },
      { title: "Preventive Care", desc: "Routine health check-ups and vaccinations." }
    ],
    technologies: ["24/7 Pathology Lab", "Advanced Digital X-Ray", "ECG & Ultrasound", "Modern ICU"],
    emergencySigns: ["Severe chest pain", "Sudden breathlessness", "Altered consciousness", "High-grade fever"],
    benefits: "Early detection prevents complications, ensuring a faster recovery and better quality of life.",
    whyChoose: ["Highly experienced MD Physicians", "Accurate and fast diagnostics", "Compassionate care", "24/7 Emergency support"],
    specialists: [{ name: "Dr. Abhishek Anand", qualifications: "MBBS", experience: "10+ Years", expertise: "General Medicine" }],
    patientCareProcess: "From accurate diagnosis to personalized treatment plans and regular follow-ups, we ensure complete care.",
    recovery: "Recovery depends on the condition; we provide continuous monitoring and dietary advice.",
    prevention: "Maintain a healthy diet, exercise regularly, and schedule annual full-body checkups.",
    faqs: [{ q: "When should I see a general physician?", a: "For any undiagnosed symptoms, persistent fever, or routine health checkups." }],
    conclusion: "Trust Avni Hospital for all your primary healthcare needs in Patna.",
    cta: "Book an Appointment with our General Physician Today.",
    images: ["/images/general-physician.png"]
  },
  "neurologist-physician": {
    id: "neurologist-physician",
    title: "Neurologist Physician",
    h1: "Best Neurologist Physician in Patna | Brain & Nerve Care",
    seoTitle: "Top Neurologist Physician in Patna | Avni Hospital",
    description: "Consult the top neurologist physicians at Avni Hospital for stroke, epilepsy, migraines, and nerve disorders.",
    keywords: "neurologist physician patna, brain doctor bihar, stroke specialist, epilepsy treatment",
    intro: "Our Neurologist Physicians specialize in diagnosing and treating disorders of the nervous system, including the brain, spinal cord, and nerves. We provide state-of-the-art care for complex neurological conditions.",
    whatIsIt: "Neurology is the branch of medicine concerned with the study and treatment of disorders of the nervous system.",
    symptoms: ["Chronic headaches", "Seizures", "Memory loss", "Numbness or tingling", "Muscle weakness"],
    causes: ["Vascular issues", "Genetics", "Infections", "Trauma", "Autoimmune disorders"],
    diagnosis: "Advanced neuro-imaging (MRI/CT), EEG, and nerve conduction studies.",
    treatments: [
      { title: "Stroke Management", desc: "Acute stroke care and rehabilitation." },
      { title: "Epilepsy Care", desc: "Medical management of seizure disorders." },
      { title: "Headache Clinics", desc: "Specialized treatment for migraines and tension headaches." }
    ],
    technologies: ["Advanced EEG", "Neuro ICU", "EMG", "High-resolution Imaging"],
    emergencySigns: ["Sudden weakness on one side", "Slurred speech", "Sudden severe headache", "Loss of consciousness"],
    benefits: "Expert neurological care can halt disease progression and drastically improve quality of life.",
    whyChoose: ["Eminent Neurologists", "Dedicated Neuro ICU", "Comprehensive Rehabilitation", "Advanced Diagnostics"],
    specialists: [{ name: "Dr. Saurabh Ranjan", qualifications: "MD, DM", experience: "12+ Years", expertise: "Neurology" }],
    patientCareProcess: "Detailed evaluation followed by targeted medical therapy and continuous rehabilitation.",
    recovery: "Neurological recovery requires time and dedicated physiotherapy, which we provide in-house.",
    prevention: "Control blood pressure, exercise regularly, and avoid smoking to protect brain health.",
    faqs: [{ q: "Do you treat migraines?", a: "Yes, we have specialized clinics for chronic headache and migraine management." }],
    conclusion: "For advanced neurological care, Avni Hospital is your trusted partner.",
    cta: "Consult our Neurologist Physician Today.",
    images: ["/images/neurologist-physician.png"]
  },
  "urologist": {
    id: "urologist",
    title: "Urologist",
    h1: "Best Urologist in Patna | Kidney & Bladder Care",
    seoTitle: "Top Urologist in Patna | Kidney Stone Treatment | Avni Hospital",
    description: "Avni Hospital offers advanced urology services, including painless kidney stone removal, prostate treatment, and bladder care by top urologists.",
    keywords: "urologist patna, kidney stone removal bihar, prostate surgery, UTI treatment",
    intro: "The Urology Department at Avni Hospital provides comprehensive care for diseases of the male and female urinary tract and the male reproductive organs. We specialize in minimally invasive treatments for fast recovery.",
    whatIsIt: "Urology focuses on surgical and medical diseases of the urinary-tract system and the reproductive organs.",
    symptoms: ["Painful urination", "Blood in urine", "Frequent urge to urinate", "Lower back or flank pain", "Incontinence"],
    causes: ["Kidney stones", "Enlarged prostate", "Urinary tract infections", "Congenital abnormalities", "Trauma"],
    diagnosis: "Ultrasound, CT Urography, Urodynamic testing, and Cystoscopy.",
    treatments: [
      { title: "Kidney Stone Removal", desc: "Laser lithotripsy and PCNL for painless stone removal." },
      { title: "Prostate Management", desc: "TURP and medical management for enlarged prostate (BPH)." },
      { title: "UTI Treatment", desc: "Comprehensive care for recurrent urinary tract infections." }
    ],
    technologies: ["Holmium Laser", "Flexible Ureteroscopes", "Advanced Lithotripters", "Urodynamic Lab"],
    emergencySigns: ["Inability to urinate", "Severe flank pain radiating to groin", "Heavy bleeding in urine"],
    benefits: "Minimally invasive urology procedures ensure no scars, minimal pain, and discharge within 24 hours.",
    whyChoose: ["Expert Uro-surgeons", "Laser-assisted surgeries", "High success rates", "Confidential care"],
    specialists: [{ name: "Dr. Ravikant Kumar Singh", qualifications: "M.S, M.Ch", experience: "15+ Years", expertise: "Endourology & Laser Surgery" }],
    patientCareProcess: "Accurate diagnosis via ultrasound, followed by laser surgery if required, and rapid discharge.",
    recovery: "Most laser urology procedures allow patients to return to normal activities within 2 to 3 days.",
    prevention: "Drink plenty of water, limit salt intake, and maintain good personal hygiene.",
    faqs: [{ q: "Is kidney stone surgery painful?", a: "No, we use advanced laser technology that requires no cuts and is virtually painless." }],
    conclusion: "Experience world-class, painless urological care at Avni Hospital.",
    cta: "Book a Consultation with our Urologist.",
    images: ["/images/urologist.png"]
  },
  "gynecologist": {
    id: "gynecologist",
    title: "Gynecologist",
    h1: "Best Gynecologist in Patna | Comprehensive Women's Health",
    seoTitle: "Top Gynecologist in Patna | Maternity Hospital | Avni Hospital",
    description: "Avni Hospital provides expert gynecological care, high-risk pregnancy management, and advanced laparoscopic surgeries for women in Patna.",
    keywords: "gynecologist patna, maternity hospital bihar, PCOD treatment, normal delivery patna",
    intro: "Our Gynecology Department is dedicated to women's health at every stage of life. From routine screenings and maternity care to advanced laparoscopic surgeries, our compassionate female doctors provide the best care.",
    whatIsIt: "Gynecology deals with the health of the female reproductive system, while obstetrics focuses on pregnancy and childbirth.",
    symptoms: ["Irregular or heavy periods", "Severe pelvic pain", "Unexplained weight gain or acne (PCOD)", "Pregnancy complications", "Menopausal symptoms"],
    causes: ["Hormonal imbalances", "Infections", "Fibroids or cysts", "Genetic factors", "Stress"],
    diagnosis: "Pelvic ultrasound, Pap smears, Colposcopy, and advanced hormonal profiling.",
    treatments: [
      { title: "Maternity Care", desc: "Comprehensive antenatal care, normal delivery, and C-section." },
      { title: "Laparoscopic Surgery", desc: "Minimally invasive removal of fibroids, cysts, and uterus (Hysterectomy)." },
      { title: "PCOD/PCOS Management", desc: "Holistic treatment for hormonal and metabolic disorders." }
    ],
    technologies: ["3D/4D Ultrasound", "Advanced Labor Rooms", "Minimally Invasive Laparoscopes", "Fetal Monitors"],
    emergencySigns: ["Heavy vaginal bleeding", "Severe abdominal pain during pregnancy", "Decreased fetal movement"],
    benefits: "Proper gynecological care ensures a healthy pregnancy, early detection of cervical cancers, and effective management of hormonal issues.",
    whyChoose: ["Highly experienced female Gynecologists", "State-of-the-art Maternity Wing", "Painless delivery options", "NICU support for newborns"],
    specialists: [{ name: "Dr. Savita Kumari", qualifications: "MBBS, MS", experience: "18+ Years", expertise: "High-Risk Pregnancy & Laparoscopy" }],
    patientCareProcess: "We provide a safe, confidential environment for women to discuss their health, supported by advanced diagnostics.",
    recovery: "Laparoscopic surgeries ensure fast recovery, usually requiring only a 1-2 day hospital stay.",
    prevention: "Regular Pap smears, maintaining a healthy BMI, and routine gynecological checkups.",
    faqs: [{ q: "Do you offer painless delivery?", a: "Yes, we offer epidural analgesia for painless and comfortable natural deliveries." }],
    conclusion: "For complete women's healthcare, Avni Hospital is Patna's most trusted choice.",
    cta: "Consult our Expert Gynecologists Today.",
    images: ["/images/gynecologist.png"]
  },
  "general-surgeon": {
    id: "general-surgeon",
    title: "General Surgeon",
    h1: "Best General Surgeon in Patna | Laparoscopic Surgery",
    seoTitle: "Top General Surgeon in Patna | Gallbladder & Hernia | Avni Hospital",
    description: "Avni Hospital offers advanced general and laparoscopic surgeries in Patna. Expert treatment for gallbladder stones, hernia, appendix, and piles.",
    keywords: "general surgeon patna, laparoscopic surgery bihar, gallbladder stone removal, hernia surgery patna",
    intro: "The Department of General Surgery specializes in performing a wide range of surgical procedures. We focus on minimally invasive laparoscopic techniques to ensure less pain, minimal scarring, and quick recovery.",
    whatIsIt: "General surgery focuses on abdominal contents including the stomach, bowels, colon, liver, gallbladder, and bile ducts, as well as the thyroid gland and hernias.",
    symptoms: ["Severe abdominal pain", "Swelling or bulges in the groin", "Painful lumps", "Bleeding during bowel movements", "Chronic acid reflux"],
    causes: ["Gallstones", "Weakness in abdominal wall (Hernia)", "Infections (Appendicitis)", "Swollen veins (Piles)"],
    diagnosis: "Ultrasound, CT Scans, Endoscopy, and comprehensive blood panels.",
    treatments: [
      { title: "Laparoscopic Gallbladder Removal", desc: "Painless, keyhole surgery for gallstones." },
      { title: "Hernia Repair", desc: "Mesh repair for all types of hernias." },
      { title: "Proctology", desc: "Advanced laser treatments for piles, fissures, and fistulas." }
    ],
    technologies: ["Advanced Laparoscopic Towers", "Harmonic Scalpels", "Laser Surgery Equipment", "Modular OTs"],
    emergencySigns: ["Sudden, excruciating lower right abdominal pain", "Inability to pass gas or stool", "Severe trauma"],
    benefits: "Laparoscopic surgeries result in tiny scars, reduced hospital stays, and a faster return to normal life.",
    whyChoose: ["Expert Laparoscopic Surgeons", "Modern OT Complex", "High success rates", "Affordable surgical packages"],
    specialists: [{ name: "Dr. Rakesh Kumar", qualifications: "M.S", experience: "16+ Years", expertise: "Advanced Laparoscopy" }],
    patientCareProcess: "Thorough pre-anesthetic checkups followed by safe surgery and careful post-operative monitoring.",
    recovery: "Most laparoscopic patients are discharged within 24 to 48 hours and recover fully in a week.",
    prevention: "Maintain a high-fiber diet, avoid heavy lifting without proper form, and stay hydrated.",
    faqs: [{ q: "What is the advantage of laparoscopy?", a: "It uses small keyhole incisions, causing less pain and allowing for much faster recovery compared to open surgery." }],
    conclusion: "For safe and advanced surgical care, trust the expert general surgeons at Avni Hospital.",
    cta: "Book a Surgical Consultation Today.",
    images: ["/images/general-surgeon.png"]
  },
  "paediatric-surgeon": {
    id: "paediatric-surgeon",
    title: "Paediatric Surgeon",
    h1: "Best Paediatric Surgeon in Patna | Child Surgery Specialists",
    seoTitle: "Top Paediatric Surgeon in Patna | Child Surgery | Avni Hospital",
    description: "Avni Hospital provides expert paediatric surgery in Patna. We handle congenital anomalies, pediatric hernias, and neonatal surgeries with extreme care.",
    keywords: "paediatric surgeon patna, child surgery bihar, neonatal surgeon patna, pediatric hernia",
    intro: "Children are not just small adults; their surgical needs are highly specialized. Our Paediatric Surgery department provides expert surgical care for fetuses, infants, children, and adolescents in a child-friendly environment.",
    whatIsIt: "Paediatric surgery is a subspecialty of surgery involving the surgery of fetuses, infants, children, adolescents, and young adults.",
    symptoms: ["Congenital deformities", "Unexplained vomiting in infants", "Inguinal hernias in children", "Undescended testes"],
    causes: ["Birth defects", "Genetics", "Infections", "Trauma in children"],
    diagnosis: "Pediatric ultrasound, specialized pediatric imaging, and gentle clinical examinations.",
    treatments: [
      { title: "Neonatal Surgery", desc: "Corrective surgeries for life-threatening birth defects." },
      { title: "General Pediatric Surgery", desc: "Treatment for hernias, hydroceles, and appendicitis in children." },
      { title: "Pediatric Urology", desc: "Correction of hypospadias and undescended testes." }
    ],
    technologies: ["Pediatric Laparoscopy", "Advanced NICU/PICU", "Child-sized surgical instruments", "Specialized pediatric anesthesia"],
    emergencySigns: ["Bilious (green) vomiting in infants", "Severe abdominal pain", "Difficulty breathing in newborns"],
    benefits: "Corrective surgeries in childhood prevent lifelong disabilities and allow children to lead normal, healthy lives.",
    whyChoose: ["Highly skilled MCh Paediatric Surgeons", "Dedicated Pediatric ICUs", "Compassionate nursing staff", "Child-friendly atmosphere"],
    specialists: [{ name: "Dr. Ashish Tiwari", qualifications: "MCh (Paediatric Surgery)", experience: "12+ Years", expertise: "Neonatal & Pediatric Laparoscopy" }],
    patientCareProcess: "We involve parents at every step, ensuring they understand the procedure, while keeping the child as comfortable as possible.",
    recovery: "Children heal remarkably fast. We provide dedicated pediatric pain management and nutritional support post-surgery.",
    prevention: "Regular antenatal checkups during pregnancy can help detect congenital anomalies early.",
    faqs: [{ q: "Is anesthesia safe for infants?", a: "Yes, our specialized pediatric anesthesiologists use highly precise, safe dosages tailored specifically for infants and children." }],
    conclusion: "Your child is in the safest hands at Avni Hospital's Paediatric Surgery department.",
    cta: "Consult our Paediatric Surgeons Today.",
    images: ["/images/paediatric-surgeon.png"]
  },
  "anaesthesia": {
    id: "anaesthesia",
    title: "Anaesthesia & Critical Care",
    h1: "Expert Anaesthesia & Critical Care in Patna",
    seoTitle: "Top Anaesthesiologists in Patna | Pain Management | Avni Hospital",
    description: "Avni Hospital's expert anesthesiologists ensure safe, pain-free surgeries and manage our advanced ICUs for critical care in Patna.",
    keywords: "anaesthesiologist patna, painless surgery bihar, critical care patna, ICU hospital bihar",
    intro: "The Department of Anaesthesia and Critical Care ensures that all surgical procedures are completely pain-free and safe. Our specialists also spearhead our Intensive Care Units (ICU), managing the most critically ill patients.",
    whatIsIt: "Anaesthesiology is the medical specialty concerned with the total perioperative care of patients before, during, and after surgery, as well as critical care medicine.",
    symptoms: ["N/A - This is a supportive and critical care specialty."],
    causes: ["N/A"],
    diagnosis: "Comprehensive Pre-Anesthetic Checkup (PAC) to assess patient fitness for surgery.",
    treatments: [
      { title: "General & Regional Anesthesia", desc: "Ensuring pain-free surgeries tailored to the patient's health profile." },
      { title: "Critical Care (ICU)", desc: "24/7 life support and monitoring for critically ill patients." },
      { title: "Pain Management", desc: "Epidurals for painless delivery and chronic pain blocks." }
    ],
    technologies: ["Advanced Anesthesia Workstations", "Multipara Monitors", "High-end Ventilators", "Syringe Pumps"],
    emergencySigns: ["Cardiac arrest", "Respiratory failure", "Severe trauma requiring immediate life support"],
    benefits: "Ensures that complex surgeries can be performed safely without the patient experiencing pain or distress.",
    whyChoose: ["Highly experienced Anaesthetists", "Modern, fully equipped ICUs", "Strict safety protocols", "24/7 presence for emergencies"],
    specialists: [{ name: "Dr. Alakh Niranjan", qualifications: "MD (Anaesthesia)", experience: "14+ Years", expertise: "Critical Care & Pain Management" }],
    patientCareProcess: "Detailed pre-surgical evaluation, continuous monitoring during surgery, and dedicated post-operative care in the recovery room.",
    recovery: "Patients are closely monitored as they wake up from anesthesia to ensure smooth recovery without nausea or pain.",
    prevention: "Provide a complete medical history to your anesthesiologist before surgery to prevent adverse reactions.",
    faqs: [{ q: "What is an epidural?", a: "An epidural is a type of regional anesthesia commonly used to provide pain relief during childbirth while keeping the mother awake." }],
    conclusion: "Safe surgeries and exceptional critical care form the backbone of Avni Hospital.",
    cta: "Learn more about our Surgical Facilities.",
    images: ["/images/anaesthesia.png"]
  },
  "dermatologist": {
    id: "dermatologist",
    title: "Skin & VD Dermatologist",
    h1: "Best Skin Specialist & Dermatologist in Patna",
    seoTitle: "Top Dermatologist in Patna | Skin & Hair Care | Avni Hospital",
    description: "Consult the best skin specialists in Patna at Avni Hospital. We treat acne, eczema, psoriasis, hair fall, and all skin/venereal diseases.",
    keywords: "dermatologist patna, skin specialist bihar, acne treatment patna, hair fall doctor, VD specialist",
    intro: "Our Dermatology department provides expert care for all diseases related to skin, hair, and nails. We also specialize in the confidential treatment of Venereal Diseases (VD).",
    whatIsIt: "Dermatology deals with the diagnosis and treatment of conditions related to the skin, hair, and nails.",
    symptoms: ["Severe acne or breakouts", "Persistent itching or rashes", "Hair thinning or bald patches", "Changes in moles", "Nail discoloration"],
    causes: ["Hormonal imbalances", "Fungal, bacterial, or viral infections", "Allergies", "Genetics", "Autoimmune conditions"],
    diagnosis: "Clinical examination, dermoscopy, skin biopsies, and allergy testing.",
    treatments: [
      { title: "Clinical Dermatology", desc: "Treatment for psoriasis, eczema, vitiligo, and fungal infections." },
      { title: "Hair & Scalp Care", desc: "Medical treatments for alopecia and severe hair fall." },
      { title: "Cosmetic Dermatology", desc: "Chemical peels, acne scar reduction, and anti-aging treatments." }
    ],
    technologies: ["Dermoscopy", "Laser Therapy", "Cryotherapy", "Advanced Pathology"],
    emergencySigns: ["Sudden, rapidly spreading rashes with fever", "Severe allergic skin reactions (anaphylaxis)"],
    benefits: "Healthy skin boosts confidence and acts as the primary barrier against infections.",
    whyChoose: ["Expert MD Dermatologists", "Evidence-based treatments", "Confidential VD care", "Modern aesthetic procedures"],
    specialists: [{ name: "Dr. Arjun Kumar", qualifications: "MBBS, MD Skin", experience: "12+ Years", expertise: "Clinical & Aesthetic Dermatology" }],
    patientCareProcess: "Accurate diagnosis of the root cause followed by targeted topical or oral medications.",
    recovery: "Skin conditions often require consistent, long-term adherence to prescribed routines for optimal results.",
    prevention: "Use sunscreen daily, maintain skin hygiene, avoid sharing personal items, and manage stress.",
    faqs: [{ q: "Can severe acne be cured completely?", a: "Yes, with targeted medical treatments and lifestyle modifications, severe acne can be effectively cured and scarring minimized." }],
    conclusion: "Achieve healthy, glowing skin with the expert dermatologists at Avni Hospital.",
    cta: "Book a Skin Consultation Today.",
    images: ["/images/dermatologist.png"]
  },
  "pulmonologist": {
    id: "pulmonologist",
    title: "Pulmonologist",
    h1: "Best Pulmonologist in Patna | Asthma & Lungs Specialist",
    seoTitle: "Top Pulmonologist in Patna | Chest Physician | Avni Hospital",
    description: "Avni Hospital features the best pulmonologists in Patna, offering expert care for asthma, COPD, tuberculosis (TB), and severe lung infections.",
    keywords: "pulmonologist patna, chest specialist bihar, asthma treatment patna, TB hospital bihar",
    intro: "The Pulmonology department provides specialized care for all respiratory and lung diseases. From chronic asthma to severe pneumonia, our chest physicians utilize advanced diagnostics to help you breathe easier.",
    whatIsIt: "Pulmonology is the medical specialty that deals with diseases involving the respiratory tract and lungs.",
    symptoms: ["Chronic cough", "Shortness of breath", "Wheezing", "Chest tightness", "Coughing up blood"],
    causes: ["Smoking", "Air pollution and allergens", "Infections (Bacteria, Viruses)", "Genetics", "Occupational hazards"],
    diagnosis: "Pulmonary Function Tests (PFT), Chest X-Rays, HRCT Thorax, and Bronchoscopy.",
    treatments: [
      { title: "Asthma & COPD Management", desc: "Advanced inhaler therapies and pulmonary rehabilitation." },
      { title: "Tuberculosis (TB) Care", desc: "Complete DOTS protocol and management of multi-drug resistant TB." },
      { title: "Sleep Apnea Treatment", desc: "Sleep studies and CPAP therapy." }
    ],
    technologies: ["Advanced PFT Lab", "Video Bronchoscopy", "High-Resolution CT Scanners", "Dedicated Respiratory ICU"],
    emergencySigns: ["Severe difficulty breathing", "Bluish lips or face", "Coughing up massive amounts of blood"],
    benefits: "Proper respiratory care improves lung capacity, reduces asthma attacks, and cures debilitating lung infections.",
    whyChoose: ["Expert Chest Physicians", "Advanced Bronchoscopy Suite", "24/7 Oxygen and Ventilator support", "Comprehensive TB Care"],
    specialists: [{ name: "Dr. Manohar Kumar", qualifications: "MD (Pulmonology)", experience: "15+ Years", expertise: "Asthma & Interventional Pulmonology" }],
    patientCareProcess: "Accurate diagnosis of lung capacity followed by targeted medical therapy and inhaler training.",
    recovery: "Chronic lung conditions require long-term management and lifestyle adjustments, supported by our rehab team.",
    prevention: "Quit smoking, wear masks in polluted areas, and avoid known allergens.",
    faqs: [{ q: "What is a Pulmonary Function Test?", a: "It is a non-invasive test that measures lung volume, capacity, and rates of flow to diagnose asthma and COPD." }],
    conclusion: "Breathe freely and live fully with the expert pulmonary care at Avni Hospital.",
    cta: "Consult our Chest Specialist Today.",
    images: ["/images/pulmonologist.png"]
  },
  "gastrologist": {
    id: "gastrologist",
    title: "Gastrologist",
    h1: "Best Gastroenterologist in Patna | Stomach & Liver Care",
    seoTitle: "Top Gastrologist in Patna | Liver & Digestive Health | Avni Hospital",
    description: "Consult the best gastroenterologists in Patna for advanced treatment of liver diseases, ulcers, acid reflux, and digestive disorders at Avni Hospital.",
    keywords: "gastrologist patna, best gastroenterologist in bihar, liver specialist patna, endoscopy bihar",
    intro: "Our Gastroenterology department provides comprehensive care for the entire digestive system, including the stomach, intestines, liver, and pancreas. We offer advanced endoscopic and medical treatments for complex digestive disorders.",
    whatIsIt: "Gastroenterology focuses on the digestive system and its disorders, ranging from the esophagus to the stomach, intestines, and liver.",
    symptoms: ["Chronic acid reflux or heartburn", "Severe abdominal pain", "Blood in stool or vomit", "Unexplained weight loss", "Jaundice (yellowing of skin)"],
    causes: ["Poor diet and irregular eating habits", "Bacterial infections (H. pylori)", "Heavy alcohol consumption", "Autoimmune diseases", "Gallstones"],
    diagnosis: "Upper GI Endoscopy, Colonoscopy, Liver Function Tests (LFT), and Abdominal Ultrasound.",
    treatments: [
      { title: "Diagnostic & Therapeutic Endoscopy", desc: "Painless procedures to detect and treat ulcers and polyps." },
      { title: "Liver Disease Management", desc: "Comprehensive care for Hepatitis, Cirrhosis, and Fatty Liver." },
      { title: "IBS & IBD Care", desc: "Targeted therapy for Irritable Bowel Syndrome and Crohn's Disease." }
    ],
    technologies: ["High-Definition Endoscopy Suites", "FibroScan for Liver", "Advanced Pathology", "24/7 GI Emergency"],
    emergencySigns: ["Vomiting large amounts of blood", "Sudden, excruciating abdominal pain", "Severe, intractable diarrhea"],
    benefits: "Effective treatment improves nutrient absorption, stops internal bleeding, and prevents the progression of liver diseases.",
    whyChoose: ["Eminent Gastroenterologists", "State-of-the-art Endoscopy Suites", "Painless, sedated procedures", "Comprehensive dietary support"],
    specialists: [{ name: "Dr. Nitin Kumar", qualifications: "MS, M.Ch", experience: "16+ Years", expertise: "Surgical Gastroenterology" }],
    patientCareProcess: "Accurate endoscopic diagnosis followed by targeted medical therapy and customized dietary planning.",
    recovery: "Endoscopic procedures are day-care. Chronic conditions require long-term dietary discipline and medication.",
    prevention: "Eat a balanced, fiber-rich diet, avoid excessive alcohol and spicy foods, and stay hydrated.",
    faqs: [{ q: "Is an endoscopy painful?", a: "No, our endoscopies are performed under mild sedation, ensuring the patient experiences no pain or discomfort." }],
    conclusion: "Restore your digestive health with the advanced gastroenterology care at Avni Hospital.",
    cta: "Book a Consultation with our Gastrologist.",
    images: ["/images/gastrologist.png"]
  },
  "neuro-surgeon": {
    id: "neuro-surgeon",
    title: "Neuro Surgeon",
    h1: "Best Neuro Surgeon in Patna | Brain & Spine Surgery",
    seoTitle: "Top Neurosurgeon in Patna | Spine Surgery | Avni Hospital",
    description: "Avni Hospital features the best neurosurgeons in Patna, specializing in complex brain tumor surgeries, spinal cord injuries, and minimally invasive spine surgeries.",
    keywords: "neuro surgeon patna, best spine surgeon bihar, brain tumor surgery patna, head trauma care",
    intro: "Our Neurosurgery department is equipped to handle the most complex surgical conditions of the brain, spine, and peripheral nerves. We utilize the latest micro-neurosurgical techniques to ensure precision and safety.",
    whatIsIt: "Neurosurgery is the medical specialty concerned with the surgical treatment of disorders affecting the brain, spinal cord, and peripheral nervous system.",
    symptoms: ["Severe, persistent headaches with vomiting", "Loss of motor skills or paralysis", "Chronic back pain radiating to the legs", "Seizures", "Head trauma after an accident"],
    causes: ["Brain or spinal tumors", "Traumatic brain injuries", "Herniated or slipped discs", "Aneurysms", "Congenital defects"],
    diagnosis: "High-resolution MRI, CT Scans, PET Scans, and Cerebral Angiography.",
    treatments: [
      { title: "Brain Tumor Surgery", desc: "Micro-surgical removal of complex brain and skull base tumors." },
      { title: "Minimally Invasive Spine Surgery", desc: "Keyhole surgeries for slipped discs and spinal stenosis." },
      { title: "Trauma Care", desc: "Emergency surgical interventions for severe head and spine injuries." }
    ],
    technologies: ["High-End Carl Zeiss Operating Microscopes", "Neuro-Navigation Systems", "Dedicated Neuro ICU", "C-Arm for Spine Surgery"],
    emergencySigns: ["Severe head injury with loss of consciousness", "Sudden paralysis", "Unequal pupil size after trauma"],
    benefits: "Expert neurosurgery can be life-saving in trauma cases and can completely restore mobility in severe spine conditions.",
    whyChoose: ["Highly experienced MCh Neurosurgeons", "Advanced Neuro-Navigation OTs", "24/7 Neuro Trauma Support", "Comprehensive Neuro-rehab"],
    specialists: [{ name: "Dr. Anil Kumar Singh", qualifications: "M.S, M.Ch", experience: "20+ Years", expertise: "Brain & Spine Micro-surgery" }],
    patientCareProcess: "Detailed surgical planning using 3D imaging, precision surgery, and dedicated post-operative care in the Neuro ICU.",
    recovery: "Neurosurgical recovery requires time and extensive in-house physiotherapy to regain motor functions.",
    prevention: "Always wear helmets/seatbelts to prevent neuro-trauma. Maintain proper posture to protect the spine.",
    faqs: [{ q: "What is minimally invasive spine surgery?", a: "It is a modern surgical technique using tiny incisions and tubular retractors to treat spine issues, resulting in less pain and faster recovery." }],
    conclusion: "Trust the precision and expertise of Avni Hospital's neurosurgeons for all brain and spine conditions.",
    cta: "Consult our Expert Neurosurgeons Today.",
    images: ["/images/neuro-surgeon.png"]
  },
  "oncologist-surgeon": {
    id: "oncologist-surgeon",
    title: "Oncologist Surgeon",
    h1: "Best Surgical Oncologist in Patna | Precision Cancer Surgery",
    seoTitle: "Top Surgical Oncologist in Patna | Tumor Surgery | Avni Hospital",
    description: "Avni Hospital offers the best surgical oncology in Patna. We specialize in the precise surgical removal of tumors, breast cancer surgery, and GI cancer surgeries.",
    keywords: "surgical oncologist patna, cancer surgery bihar, tumor removal patna, breast cancer surgeon",
    intro: "Surgical Oncology is a critical pillar of cancer treatment. Our highly skilled surgical oncologists specialize in the precise, curative excision of solid tumors, working closely with medical oncologists to ensure the best possible outcomes.",
    whatIsIt: "Surgical oncology focuses on the surgical management of tumors, especially cancerous tumors, by removing them and surrounding tissues.",
    symptoms: ["Palpable lumps or masses", "Changes in breast tissue", "Unexplained bleeding", "Difficulty swallowing", "Visible skin changes"],
    causes: ["Genetic mutations", "Environmental carcinogens", "Tobacco and alcohol use", "Chronic inflammation"],
    diagnosis: "Biopsies, PET-CT Scans, MRI, and precise pre-surgical staging.",
    treatments: [
      { title: "Breast Cancer Surgery", desc: "Mastectomy and breast conservation surgeries." },
      { title: "GI Malignancies", desc: "Complex surgeries for stomach, colon, and liver cancers." },
      { title: "Head & Neck Surgery", desc: "Curative surgeries for oral, thyroid, and laryngeal cancers." }
    ],
    technologies: ["State-of-the-art Modular OTs", "Frozen Section Biopsy Lab", "Advanced Electrocautery Systems", "Post-op ICU"],
    emergencySigns: ["Severe obstruction caused by a tumor", "Massive bleeding from a tumor site"],
    benefits: "Surgical removal of localized tumors is often the most effective method for completely curing cancer in its early stages.",
    whyChoose: ["Eminent MCh Surgical Oncologists", "Multidisciplinary Tumor Board", "Zero-infection OTs", "Compassionate post-op care"],
    specialists: [{ name: "Dr. Praveen Kumar", qualifications: "M.S, M.Ch", experience: "16+ Years", expertise: "Complex Surgical Oncology" }],
    patientCareProcess: "Comprehensive staging, surgical planning, tumor excision, and collaboration with medical oncologists for follow-up care.",
    recovery: "Recovery depends on the extent of the surgery. We provide extensive nutritional support, pain management, and wound care.",
    prevention: "Regular screenings (mammograms, colonoscopies) can detect tumors early when they are most easily surgically removed.",
    faqs: [{ q: "What is breast conservation surgery?", a: "It is a surgical procedure that removes only the cancerous tumor and a small margin of healthy tissue, preserving the rest of the breast." }],
    conclusion: "For precise and curative cancer surgeries, Avni Hospital is your most trusted destination in Patna.",
    cta: "Book a Consultation with our Surgical Oncologist.",
    images: ["/images/oncologist-surgeon.png"]
  },
  "nephrologist": {
    id: "nephrologist",
    title: "Nephrologist",
    h1: "Best Nephrologist in Patna | Kidney Disease Specialist",
    seoTitle: "Top Nephrologist in Patna | Dialysis Center | Avni Hospital",
    description: "Avni Hospital has the best nephrologists in Patna, offering comprehensive care for chronic kidney disease, advanced dialysis, and kidney failure management.",
    keywords: "nephrologist patna, kidney specialist bihar, dialysis center patna, CKD treatment bihar",
    intro: "Our Nephrology department provides expert, continuous care for all kidney-related disorders. Equipped with a state-of-the-art dialysis unit, we offer life-saving treatments for patients with acute and chronic kidney diseases.",
    whatIsIt: "Nephrology is the medical specialty that focuses on diagnosing and treating diseases of the kidneys.",
    symptoms: ["Swelling in legs, ankles, or face (Edema)", "Changes in urination frequency", "Severe fatigue and weakness", "High blood pressure", "Metallic taste in mouth"],
    causes: ["Uncontrolled Diabetes (Diabetic Nephropathy)", "Severe Hypertension", "Glomerulonephritis", "Polycystic Kidney Disease", "Prolonged use of painkillers"],
    diagnosis: "Kidney Function Tests (KFT), Glomerular Filtration Rate (GFR) testing, Ultrasound, and Kidney Biopsy.",
    treatments: [
      { title: "Chronic Kidney Disease (CKD) Management", desc: "Medical management to slow the progression of kidney failure." },
      { title: "Hemodialysis", desc: "State-of-the-art dialysis for end-stage renal disease (ESRD)." },
      { title: "Hypertension Control", desc: "Specialized management of kidney-related high blood pressure." }
    ],
    technologies: ["Advanced Hemodialysis Machines", "Dedicated RO Water Plant for Dialysis", "24/7 Dialysis Unit", "Advanced Pathology Lab"],
    emergencySigns: ["Complete cessation of urine", "Severe shortness of breath due to fluid overload", "Confusion or seizures from uremia"],
    benefits: "Expert nephrology care can delay the need for dialysis, and our advanced dialysis unit significantly improves the quality of life for ESRD patients.",
    whyChoose: ["Highly experienced DM Nephrologists", "Hygienic and safe 24/7 Dialysis Center", "Comprehensive nutritional counseling", "Strict infection control"],
    specialists: [{ name: "Dr. Raja Ram Yadav", qualifications: "MD, DM", experience: "14+ Years", expertise: "Clinical Nephrology & Dialysis" }],
    patientCareProcess: "Early detection of declining kidney function, followed by strict dietary management, medication, and dialysis if necessary.",
    recovery: "Kidney disease often requires lifelong management. Dialysis patients receive ongoing support and monitoring from our dedicated team.",
    prevention: "Control blood sugar and blood pressure, stay hydrated, and avoid over-the-counter painkillers.",
    faqs: [{ q: "How often is dialysis needed?", a: "Typically, hemodialysis is performed three times a week, with each session lasting about 4 hours." }],
    conclusion: "Trust Avni Hospital for compassionate and advanced kidney care in Patna.",
    cta: "Schedule a Consultation with our Nephrologist.",
    images: ["/images/doctor-preparing-consult1.svg"]
  },
  "junior-resident": {
    id: "junior-resident",
    title: "Junior Resident",
    h1: "Dedicated 24/7 Junior Residents | Continuous Patient Care",
    seoTitle: "24/7 Junior Resident Doctors in Patna | Avni Hospital",
    description: "Avni Hospital is supported by a dedicated team of junior residents available 24/7 to provide continuous monitoring and immediate primary care.",
    keywords: "junior resident doctors patna, 24/7 doctor availability bihar, hospital emergency doctors, ward medical officers",
    intro: "Our dedicated team of Junior Resident Doctors forms the backbone of continuous patient care at Avni Hospital. Available 24/7 across all wards and intensive care units, they ensure that every patient receives immediate medical attention, round-the-clock monitoring, and compassionate care.",
    whatIsIt: "Junior Residents are qualified medical doctors (MBBS/MD) who work closely under the supervision of senior consultants to manage the day-to-day medical needs of admitted patients.",
    symptoms: ["N/A - They handle primary triage and ongoing care for all symptoms."],
    causes: ["N/A"],
    diagnosis: "First-line clinical evaluation, emergency triage, and continuous monitoring of patient vitals.",
    treatments: [
      { title: "Emergency Triage", desc: "Immediate assessment and stabilization of emergency patients." },
      { title: "Ward Management", desc: "Continuous round-the-clock monitoring of admitted patients." },
      { title: "Surgical Assistance", desc: "Assisting senior surgeons in major surgical procedures." }
    ],
    technologies: ["Full access to all hospital emergency and diagnostic technologies."],
    emergencySigns: ["First responders to all in-hospital emergencies, including code blues and rapid response situations."],
    benefits: "Ensures that patients are never left unmonitored. Immediate medical intervention is available 24 hours a day, drastically improving patient safety.",
    whyChoose: ["Highly qualified and energetic medical professionals", "Available 24/7 on the hospital premises", "Instant response to patient needs", "Seamless coordination with senior specialists"],
    specialists: [{ name: "Dr. Upesh Kumar", qualifications: "MBBS", experience: "Resident", expertise: "Emergency & Ward Care" }],
    patientCareProcess: "Residents conduct frequent ward rounds, monitor patient progress, manage acute issues, and immediately consult senior doctors when required.",
    recovery: "Continuous monitoring by residents ensures that the recovery trajectory is maintained and any complications are caught early.",
    prevention: "N/A",
    faqs: [{ q: "Are resident doctors available at night?", a: "Yes, our junior residents are on duty 24/7, ensuring complete medical coverage during the night." }],
    conclusion: "At Avni Hospital, you are under constant, vigilant care every second of your stay.",
    cta: "Learn more about our 24/7 Facilities.",
    images: ["/images/smiling-young-male-doctor-wearing-stethoscope-medical-gown-isolated-white-wall1.svg"]
  }
};
